(()=>{"use strict";
const branch="beta/v1.1.0-beta.1",base="https://raw.githubusercontent.com/ByD4rking/Iptv-Chile-Master-CL/"+branch+"/";
const playlists=[
["principal","🇨🇱 Principal corregida","IPTV-CHILE-MAESTRA_CORREGIDO.m3u"],["god","🛡️ GOD","IPTV-CHILE-MAESTRA_GOD.m3u"],["generador","⚙️ Generador beta","IPTV-CHILE-GENERADOR/IPTV-CHILE-GENERADOR.m3u"],
["pluto_latam","🌎 Pluto LATAM","pluto/output/playlists/pluto_latam.m3u"],["pluto_cl","🇨🇱 Pluto Chile","pluto/output/playlists/pluto_cl.m3u"],["pluto_es","🇪🇸 Pluto España","pluto/output/playlists/pluto_es.m3u"],["pluto_mx","🇲🇽 Pluto México","pluto/output/playlists/pluto_mx.m3u"],["pluto_ar","🇦🇷 Pluto Argentina","pluto/output/playlists/pluto_ar.m3u"],["pluto_br","🇧🇷 Pluto Brasil","pluto/output/playlists/pluto_br.m3u"],["pluto_us","🇺🇸 Pluto USA","pluto/output/playlists/pluto_us.m3u"]];
const playlistEl=document.getElementById("playlist"),filterEl=document.getElementById("filter"),channelsEl=document.getElementById("channels"),video=document.getElementById("video"),status=document.getElementById("status"),meta=document.getElementById("meta"),rawLink=document.getElementById("rawLink");let hls=null,entries=[];
for(const [id,name] of playlists){const o=document.createElement("option");o.value=id;o.textContent=name;playlistEl.appendChild(o)}
function parseAttrs(line){const attrs={},m=line.match(/^#EXTINF:[^,]*,(.*)$/);attrs.name=m?m[1].trim():"Canal";const head=line.split(",",1)[0],re=/([\w-]+)="([^"]*)"/g;let x;while((x=re.exec(head)))attrs[x[1]]=x[2];return attrs}
function parseM3U(text){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/),out=[];for(let i=0;i<lines.length;i++){if(!lines[i].startsWith("#EXTINF:"))continue;const a=parseAttrs(lines[i]);let url="";for(let j=i+1;j<lines.length;j++){const l=lines[j].trim();if(!l)continue;if(l.startsWith("#"))continue;url=l;break}if(/^https?:\/\//i.test(url))out.push({name:a.name||"Canal",logo:a["tvg-logo"]||"",group:a["group-title"]||"Sin categoría",url})}return out}
function setStatus(x){status.textContent=x}function destroy(){if(hls){hls.destroy();hls=null}video.removeAttribute("src");video.load()}
function play(entry){destroy();meta.textContent=entry.group+" · "+entry.url;setStatus("Conectando: "+entry.name);document.querySelectorAll(".channel").forEach(x=>x.classList.remove("active"));const active=[...document.querySelectorAll(".channel")].find(x=>x.dataset.url===entry.url);if(active)active.classList.add("active");
if(window.Hls&&Hls.isSupported()&&/\.m3u8(?:$|\?)/i.test(entry.url)){hls=new Hls({enableWorker:true,lowLatencyMode:true});hls.loadSource(entry.url);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>{setStatus("▶ Reproduciendo: "+entry.name);video.play().catch(()=>{})});hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal)setStatus("❌ Error HLS: "+(d.details||"stream no disponible"))});return}
if(/\.m3u8(?:$|\?)/i.test(entry.url)&&video.canPlayType("application/vnd.apple.mpegurl")){video.src=entry.url;video.addEventListener("loadedmetadata",()=>{setStatus("▶ Reproduciendo: "+entry.name);video.play().catch(()=>{})},{once:true});return}
video.src=entry.url;video.addEventListener("loadedmetadata",()=>setStatus("▶ Reproduciendo: "+entry.name),{once:true});video.play().catch(()=>setStatus("Pulsa Play para iniciar: "+entry.name))}
function render(){const q=filterEl.value.trim().toLowerCase();channelsEl.textContent="";const filtered=entries.filter(x=>(x.name+" "+x.group).toLowerCase().includes(q));for(const entry of filtered){const b=document.createElement("button");b.type="button";b.className="channel";b.dataset.url=entry.url;const img=document.createElement("img");img.alt="";img.loading="lazy";img.referrerPolicy="no-referrer";if(entry.logo)img.src=entry.logo;const span=document.createElement("span");span.textContent=entry.name;const small=document.createElement("small");small.textContent=entry.group;span.appendChild(small);b.append(img,span);b.addEventListener("click",()=>play(entry));channelsEl.appendChild(b)}setStatus(filtered.length+" canales visibles · "+entries.length+" totales")}
async function loadPlaylist(){destroy();entries=[];render();const selected=playlists.find(x=>x[0]===playlistEl.value)||playlists[0],url=base+selected[2];rawLink.href=url;setStatus("Cargando "+selected[1]+"…");try{const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error("HTTP "+r.status);entries=parseM3U(await r.text());if(!entries.length)throw new Error("No se encontraron entradas M3U.");render();setStatus(entries.length+" canales cargados.")}catch(e){setStatus("❌ No se pudo cargar la playlist: "+e.message)}}
playlistEl.addEventListener("change",loadPlaylist);filterEl.addEventListener("input",render);document.getElementById("reload").addEventListener("click",loadPlaylist);loadPlaylist();
})();