from __future__ import annotations

import json
import re
from pathlib import Path

from channels import GROUPS, normalize_channel
from client import PlutoClient
from regions import REGIONS, Region


BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "output"
PLAYLIST_DIR = OUTPUT_DIR / "playlists"
REGIONAL_DATA_DIR = OUTPUT_DIR / "regional"

# Do not replace a known-good playlist with a catastrophic partial response.
MIN_PREVIOUS_RATIO = 0.50

# No maximum channel count: every valid channel returned by Pluto is eligible.

# Reference playlist used only for presentation metadata: group/folder, order and logo.
# Streams continue to be generated by our own Pluto client.

REFERENCE_CATEGORY_MAP = {
    "anime & gaming": "Anime",
    "anime": "Anime",
    "gaming": "Anime",
    "entertainment": "Entretenimiento",
    "entretenimiento": "Entretenimiento",
    "movies": "Cine",
    "movie": "Cine",
    "peliculas": "Cine",
    "películas": "Cine",
    "cine": "Cine",
    "kids": "Infantil",
    "infantil": "Infantil",
    "sports": "Deportes",
    "deportes": "Deportes",
    "news": "Noticias",
    "noticias": "Noticias",
    "music": "Música",
    "música": "Música",
    "series": "Series",
    "comedy": "Comedia",
    "comedia": "Comedia",
    "reality": "Reality",
    "retro": "Retro",
    "teen": "Teen",
    "telenovelas": "Novelas",
    "novelas": "Novelas",
    "investigation": "Investigación",
    "investigación": "Investigación",
    "paranormal": "Zona Paranormal",
    "westerns": "Cine",
    "western": "Cine",
    "true crime": "Investigación",
    "crime drama": "Series",
    "sci-fi + fantasy": "Cine",
    "drama": "Series",
    "movies": "Cine",
    "south park": "South Park",
    "comedy": "Comedia",
    "kids": "Infantil",
    "kids en français": "Infantil",
    "local news": "Noticias",
    "news + opinion": "Noticias",
    "informativos": "Informativos",
    "informativo": "Informativos",
    "game shows": "Competencia",
    "classic tv comedy": "Comedia",
    "home + food": "Estilo De Vida",
    "daytime & talk shows": "Entretenimiento",
    "classic tv": "Retro",
    "competition reality": "Competencia",
    "sports": "Deportes",
    "documentary + science": "Documentales",
    "documentary": "Documentales",
    "documentales": "Documentales",
    "reality": "Reality",
    "music": "Música",
    "mtv": "Música",
    "mtv en pluto tv": "Música",
    "natureza": "Curiosidad",
    "nature": "Curiosidad",
    "curiosidades": "Curiosidad",
    "investigação": "Investigación",
    "esportes": "Deportes",
    "comédia": "Comedia",
    "filmes": "Cine",
    "retrô": "Retro",
    "infantil": "Infantil",
    "jornada nas estrelas": "Series",
    "mistérios e sobrenatural": "Zona Paranormal",
    "séries": "Series",
    "nickelodeon": "Infantil",
    "tv brasileira": "Entretenimiento",
    "mtv vma 2026": "Música",
    "policiacas": "Investigación",
    "crimen y misterio": "Investigación",
    "cultura": "Cultura",
    "culture": "Cultura",
    "ciencia ficción": "Cine",
    "nuevo en pluto tv": "Entretenimiento",
}


def normalize_reference_category(reference_group: str, channel: dict) -> str:
    raw = re.sub(r"\s+", " ", str(reference_group or "").strip().lower())
    mapped = REFERENCE_CATEGORY_MAP.get(raw)
    if mapped:
        return mapped

    # If the reference uses a combined/unknown folder, fall back to the same
    # semantic classifier used for channels, based on name/description/source category.
    return channel.get("category") or "Entretenimiento"


def fetch_reference_metadata(region: Region) -> tuple[dict[str, dict], dict[str, int], dict[str, int]]:
    """Read our existing regional playlist for presentation metadata.

    This deliberately uses only playlists already generated by this repository;
    no third-party M3U is consulted or used to add channels.
    """
    path = PLAYLIST_DIR / f"pluto_{region.code}.m3u"
    if not path.exists() or path.stat().st_size == 0:
        print(f"[{region.code.upper()}] Referencia propia: no existe una lista previa")
        return {}, {}, {}
    text = path.read_text(encoding="utf-8-sig", errors="replace")
    metadata: dict[str, dict] = {}
    group_order: dict[str, int] = {}
    channel_order: dict[str, int] = {}
    position = 0
    for line in text.splitlines():
        if not line.startswith("#EXTINF:"):
            continue
        id_match = re.search(r'tvg-id="([^"]+)"', line)
        if not id_match:
            continue
        channel_id = id_match.group(1)
        group_match = re.search(r'group-title="([^"]*)"', line)
        logo_match = re.search(r'tvg-logo="([^"]*)"', line)
        name_match = re.search(r'tvg-name="([^"]*)"', line)
        group = (group_match.group(1).strip() if group_match else "") or "Otros"
        logo = logo_match.group(1).strip() if logo_match else ""
        name = name_match.group(1).strip() if name_match else ""
        if group not in group_order:
            group_order[group] = len(group_order)
        metadata[channel_id] = {"category": group, "logo": logo, "reference_name": name}
        channel_order[channel_id] = position
        position += 1
    print(f"[{region.code.upper()}] Referencia propia: {len(metadata)} canales, {len(group_order)} carpetas/grupos")
    return metadata, group_order, channel_order

def apply_reference_metadata(
    channels: list[dict],
    region: Region,
) -> tuple[list[dict], int, int]:
    metadata, group_order, channel_order = fetch_reference_metadata(region)
    if not metadata:
        return channels, 0, 0

    matched = 0
    logos = 0

    for channel in channels:
        ref = metadata.get(channel.get("id", ""))
        if not ref:
            # Some regional Pluto IDs can change. Fall back to a unique normalized name match.
            name = re.sub(r"\\s+", " ", str(channel.get("name") or "").strip().lower())
            candidates = [m for m in metadata.values() if re.sub(r"\\s+", " ", str(m.get("reference_name") or "").strip().lower()) == name]
            if len(candidates) == 1:
                ref = candidates[0]
        if not ref:
            continue

        matched += 1

        # Use the reference only as a semantic hint. Normalize its folders into
        # our canonical Spanish categories instead of copying arbitrary names.
        channel["category"] = normalize_reference_category(
            ref.get("category", ""),
            channel,
        )
        channel["reference_group_order"] = group_order.get(ref["category"], 999999)
        channel["reference_channel_order"] = channel_order.get(channel.get("id", ""), 999999)

        # Prefer the reference logo; keep our existing logo if the reference has none.
        if ref.get("logo"):
            if channel.get("logo") != ref["logo"]:
                logos += 1
            channel["logo"] = ref["logo"]

    # Channels not present in the reference remain in our existing category structure.
    for channel in channels:
        channel.setdefault("reference_group_order", 999999)
        channel.setdefault("reference_channel_order", 999999)

    print(
        f"[{region.code.upper()}] Coincidencias con referencia: {matched}; "
        f"logos actualizados: {logos}"
    )
    return channels, matched, logos


def fetch_region(region: Region) -> list[dict]:
    client = PlutoClient(region)
    print(f"[{region.code.upper()}] Obteniendo canales...")
    raw = client.get_channels()
    print(f"[{region.code.upper()}] Canales devueltos por Pluto: {len(raw)}")

    normalized = []
    rejected = 0
    seen_ids = set()

    for channel in raw:
        channel_id = channel.get("id")
        if not channel_id or channel_id in seen_ids:
            continue
        try:
            item = normalize_channel(client, channel)
            normalized.append(item)
            seen_ids.add(channel_id)
        except Exception as exc:
            rejected += 1
            print(f"[{region.code.upper()}] No se pudo procesar {channel_id}: {exc}")

    normalized, _, _ = apply_reference_metadata(normalized, region)

    print(
        f"[{region.code.upper()}] Canales válidos incorporables: "
        f"{len(normalized)}; rechazados: {rejected}"
    )
    return normalized


def valid_stream(stream: str) -> bool:
    return bool(
        stream
        and stream.startswith(("http://", "https://"))
        and ".m3u8" in stream
    )


def esc(value) -> str:
    return "" if value is None else str(value).replace('"', "'").strip()


def channel_to_m3u(channel: dict, region: Region) -> str:
    channel_id = esc(channel.get("id"))
    name = esc(channel.get("name"))
    stream = esc(channel.get("stream"))
    logo = esc(channel.get("logo")) or f"https://images.pluto.tv/channels/{channel_id}/colorLogoPNG.png"
    group = esc(channel.get("category")) or "Entretenimiento"

    if not channel_id or not name or not valid_stream(stream):
        return ""

    return (
        f'#EXTINF:-1 tvg-id="{channel_id}" tvg-name="{name}" '
        f'tvg-logo="{logo}" group-title="{group}",{name}\n'
        f'{stream}\n'
    )


def sort_key(channel: dict) -> tuple:
    # When the reference has this channel, reproduce its folder order and channel order.
    if channel.get("reference_group_order", 999999) < 999999:
        return (
            channel.get("reference_group_order", 999999),
            channel.get("reference_channel_order", 999999),
            str(channel.get("name") or "").lower(),
        )

    group = channel.get("category") or "Otros"
    group_index = GROUPS.index(group) if group in GROUPS else len(GROUPS)
    try:
        number = int(channel.get("number"))
    except (TypeError, ValueError):
        number = 999999
    return (100000 + group_index, number, str(channel.get("name") or "").lower())


def previous_count(path: Path) -> int:
    if not path.exists():
        return 0
    try:
        text = path.read_text(encoding="utf-8-sig")
        return len(re.findall(r"^#EXTINF:", text, flags=re.MULTILINE))
    except Exception:
        return 0


def build_playlist(channels: list[dict], region: Region) -> str:
    ordered = sorted(channels, key=sort_key)
    lines = ["#EXTM3U"]
    seen = set()

    for channel in ordered:
        stream = channel.get("stream") or ""
        channel_id = channel.get("id") or ""
        key = channel_id or stream
        if key in seen:
            continue
        entry = channel_to_m3u(channel, region)
        if entry:
            lines.append(entry.rstrip())
            seen.add(key)

    if len(seen) == 0:
        raise RuntimeError(f"{region.code.upper()}: no hay canales válidos.")

    return "\n".join(lines) + "\n"


def write_if_safe(region: Region, channels: list[dict]) -> tuple[Path, int, bool]:
    PLAYLIST_DIR.mkdir(parents=True, exist_ok=True)
    REGIONAL_DATA_DIR.mkdir(parents=True, exist_ok=True)

    playlist_path = PLAYLIST_DIR / f"pluto_{region.code}.m3u"
    data_path = REGIONAL_DATA_DIR / f"channels_{region.code}.json"

    content = build_playlist(channels, region)
    new_count = content.count("#EXTINF:")
    old_count = previous_count(playlist_path)

    if old_count and new_count < max(1, int(old_count * MIN_PREVIOUS_RATIO)):
        print(
            f"[{region.code.upper()}] BLOQUEADO: {new_count} canales nuevos "
            f"frente a {old_count} anteriores. Se conserva la lista anterior."
        )
        return playlist_path, old_count, False

    tmp_playlist = playlist_path.with_suffix(".m3u.tmp")
    tmp_data = data_path.with_suffix(".json.tmp")

    tmp_playlist.write_text(content, encoding="utf-8")
    tmp_data.write_text(
        json.dumps(channels, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    tmp_playlist.replace(playlist_path)
    tmp_data.replace(data_path)

    print(f"[{region.code.upper()}] {new_count} canales -> {playlist_path}")
    return playlist_path, new_count, True


def build_latam() -> Path:
    """Build a Spanish-speaking Latin America aggregate from verified regional lists.

    This is an aggregate playlist, not a claim that Pluto exposes a separate
    official LATAM market. It uses only the regional playlists we already
    generate and deduplicates by tvg-id (falling back to stream URL).
    """
    PLAYLIST_DIR.mkdir(parents=True, exist_ok=True)

    source_codes = ("mx", "cl", "ar")
    lines = ["#EXTM3U"]
    seen = set()
    source_counts = {}

    for code in source_codes:
        path = PLAYLIST_DIR / f"pluto_{code}.m3u"
        if not path.exists():
            source_counts[code] = 0
            continue

        text = path.read_text(encoding="utf-8-sig")
        chunks = re.split(r"(?=^#EXTINF:)", text, flags=re.MULTILINE)
        added_from_source = 0

        for chunk in chunks:
            if not chunk.startswith("#EXTINF:"):
                continue
            lines_chunk = chunk.strip().splitlines()
            if len(lines_chunk) < 2:
                continue

            match = re.search(r'tvg-id="([^\"]+)"', lines_chunk[0])
            key = match.group(1) if match else lines_chunk[1].strip()
            if key in seen:
                continue

            lines.extend(lines_chunk[:2])
            seen.add(key)
            added_from_source += 1

        source_counts[code] = added_from_source

    if not seen:
        raise RuntimeError("LATAM: no hay canales regionales válidos para construir la lista.")

    output = PLAYLIST_DIR / "pluto_latam.m3u"
    tmp = output.with_suffix(".m3u.tmp")
    tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    tmp.replace(output)

    print(
        f"[LATAM] {len(seen)} canales únicos -> {output} "
        f"(MX: {source_counts.get('mx', 0)}, CL: {source_counts.get('cl', 0)}, "
        f"AR: {source_counts.get('ar', 0)})"
    )
    return output


def build_all() -> Path:
    PLAYLIST_DIR.mkdir(parents=True, exist_ok=True)

    paths = [PLAYLIST_DIR / f"pluto_{code}.m3u" for code in REGIONS]
    lines = ["#EXTM3U"]
    seen_ids = set()
    total = 0

    for path in paths:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8-sig")
        chunks = re.split(r"(?=^#EXTINF:)", text, flags=re.MULTILINE)

        for chunk in chunks:
            if not chunk.startswith("#EXTINF:"):
                continue

            lines_chunk = chunk.strip().splitlines()
            if len(lines_chunk) < 2:
                continue

            match = re.search(r'tvg-id="([^"]+)"', lines_chunk[0])
            key = match.group(1) if match else lines_chunk[1]

            if key in seen_ids:
                continue

            lines.extend(lines_chunk[:2])
            seen_ids.add(key)
            total += 1

    if total == 0:
        raise RuntimeError("No hay listas regionales válidas para construir pluto_all.m3u.")

    output = PLAYLIST_DIR / "pluto_all.m3u"
    tmp = output.with_suffix(".m3u.tmp")
    tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    tmp.replace(output)

    # Do not overwrite the existing legacy pluto.m3u automatically.
    # Regional playlists are additive; the legacy list remains untouched.
    print(f"[ALL] {total} canales únicos -> {output}")
    return output


def main() -> None:
    print("================================")
    print("PLUTO TV MULTIRREGIONAL")
    print("================================")

    results = {}
    for code in ("es", "mx"):
        region = REGIONS[code]
        try:
            channels = fetch_region(region)
            path, count, updated = write_if_safe(region, channels)
            results[code] = (count, updated)
        except Exception as exc:
            print(f"[{code.upper()}] ERROR: {exc}")
            results[code] = (0, False)

    failed_regions = [code for code, (count, updated) in results.items() if count <= 0]
    if failed_regions:
        raise RuntimeError(
            "No se publican agregados: regiones sin catálogo válido: "
            + ", ".join(failed_regions)
        )

    build_latam()

    print()
    print("RESUMEN")
    for code, (count, updated) in results.items():
        state = "actualizada" if updated else "conservada/no actualizada"
        print(f"{code.upper()}: {count} canales - {state}")


if __name__ == "__main__":
    main()
